#!/usr/bin/env bash

echo "== delete objects =="

set -e

# check for bucket name
if [ -z "$1" ]; then
    echo "There need to be a bucket name."
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 --bucket kirusha-bucket --query Contents[].Key | jq -n '{ Objects: [inputs | .[] | {Key: .}] }' > /tmp/delete.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete.json
