#!/usr/bin/env bash

echo "== delete bucket=="

# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name e.g. ./delete-bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
     --bucket $BUCKET_NAME